version: 0.2
env:
  variables:
    CACHE_CONTROL: "86400"
    S3_BUCKET: "{{s3_bucket_url}}"
    BUILD_FOLDER: "build"
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started
      - npm run build
artifacts:
  files:
    - "**/*"
  base-directory: "build*"
  discard-paths: yes
